apiVersion: v1
metadata:
   name: frontend-svc
   labels:
     type: svc-lb
kind: Service
spec:
    type: LoadBalancer
    selector:
        pod: frontend
    ports:
    - port: 80
      targetPort: 8080
      name: http-web